In [20]:
import numpy 
numpy.random.seed(1337)

In [21]:
import h5py
import keras
from keras.models import Sequential, Model
from keras.layers import Dense, Activation, Flatten, Input, MaxPooling2D, Dropout, AveragePooling2D, GlobalAveragePooling2D
from keras.layers import Conv2D, Embedding
from keras.optimizers import SGD, rmsprop
from sklearn.metrics import classification_report, confusion_matrix, precision_recall_fscore_support, accuracy_score, f1_score, precision_score, recall_score
from sklearn.utils import class_weight
from sklearn.utils.class_weight import compute_class_weight
from sklearn.preprocessing import LabelEncoder
from keras.layers.advanced_activations import LeakyReLU, PReLU, ELU
from keras_contrib.layers.advanced_activations import PELU, SReLU

In [29]:
batch_size=10
num_classes=39
epochs=30

In [23]:
import os
from PIL import Image
import matplotlib.image as mpimg

In [123]:
os.chdir("E:");
#path="E:/Dataset_Final(March)/One";
path="E:/Dummy/Dataset2";
classes=os.listdir(path)
x=[]#Datapoints 
y=[]#labels 
for fol in classes:
    imgfiles=os.listdir(path+u'\\'+fol);
    for img in imgfiles:
        im=mpimg.imread(path+u'\\'+fol+u'\\'+img);
        x.append(im)
        y.append(fol)
x=numpy.array(x)
y=numpy.array(y)

In [124]:
print(x.shape)
print(y.shape)
x=x.reshape((-1,100,100,1))

(152, 100, 100)
(152,)


In [125]:
n=x.shape[0]
randomize=numpy.arange(n)
numpy.random.shuffle(randomize)
randomize
x=x[randomize]
y=y[randomize]

In [126]:
test_split=round(n*2/3)
x_train=x[:test_split]
y_train=y[:test_split]
x_test=x[test_split:]
y_test=y[test_split:]

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(101, 100, 100, 1)
(101,)
(51, 100, 100, 1)
(51,)


In [127]:
y_train=keras.utils.to_categorical(y_train, num_classes)
y_test=keras.utils.to_categorical(y_test, num_classes)
y_train[:1]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [128]:
# from keras.preprocessing.image import ImageDataGenerator

# datagen = ImageDataGenerator(
#         rotation_range=40,
#         width_shift_range=0.2,
#         height_shift_range=0.2,
#         rescale=1./255,
#         shear_range=0.2,
#         zoom_range=0.2,
#         horizontal_flip=True,
#         fill_mode='nearest')
# datagen.fit(x_train)

In [129]:
# inputs=Input(shape=(100,100,1))
# x=Conv2D(32, (6, 6), padding='same', strides=1)(inputs)
# x=SReLU()(x)
# x=Conv2D(32, (6, 6), padding='same')(x)
# x=SReLU()(x)
# x=MaxPooling2D(pool_size=(2,2), strides=1)(x)
# x=Dropout(0.2)(x)
# x=Conv2D(24, (3, 3), padding='same', strides=1)(x)
# x=SReLU()(x)
# x=Conv2D(24, (3, 3), padding='same')(x)
# x=SReLU()(x)
# x=MaxPooling2D(pool_size=(2,2), strides=1)(x)
# x=Dropout(0.2)(x)

# x=Flatten()(x)#-------------------------------------------------------------------------------0.58(ep-37)
# x=Dense(256)(x)
# x=SReLU()(x)
# x=Dense(num_classes)(x)

# output=Activation('softmax')(x)
# model=Model([inputs], output)

In [130]:
# inputs=Input(shape=(100,100,1))

# x=Conv2D(128,(3,3), padding='same')(inputs)
# x=SReLU()(x)
# x=Conv2D(64,(3,3))(x)
# x=SReLU()(x)
# x=MaxPooling2D(pool_size=(2,2))(x)
# x=Dropout(0.2)(x)
# x=Flatten()(x)
# x=Dense(num_classes)(x)
# #x=Activation('softmax')(x)
# output=Activation('softmax')(x)
# model=Model([inputs], output)

In [131]:
# inputs=Input(shape=(100,100,1))
# x=Conv2D(16, (3, 3), padding='same')(inputs)
# x=Conv2D(16, (3, 3), padding='same')(x)
# x=MaxPooling2D(pool_size=(2,2))(x)
# x=Conv2D(32, (3, 3), padding='same')(x)
# x=Conv2D(32, (3, 3), padding='same')(x)
# x=MaxPooling2D(pool_size=(2,2))(x)
# x=Conv2D(64, (3, 3), padding='same')(x)
# x=Conv2D(64, (3, 3), padding='same')(x)
# x=MaxPooling2D(pool_size=(2,2))(x)
# x=Conv2D(72, (3, 3), padding='same')(x)
# x=Conv2D(72, (3, 3), padding='same')(x)
# x=MaxPooling2D(pool_size=(2,2))(x)
# x=Conv2D(94, (3, 3), padding='same')(x)
# x=Conv2D(94, (3, 3), padding='same')(x)
# x=MaxPooling2D(pool_size=(2,2))(x)
# x=Dropout(0.2)(x)
# x=SReLU()(x)
# x=Flatten()(x)-----------------------------------------------0.60(ep-38)
# # x=Dense(37)(x)
# # x=SReLU()(x)

# x=Dense(num_classes)(x)
# #x=SReLU()(x)
# output=Activation('softmax')(x)
# model=Model([inputs], output)

In [132]:
# inputs=Input(shape=(100,100,1))
# x=Conv2D(16, (3, 3), padding='same')(inputs)
# x=Conv2D(16, (3, 3), padding='same')(x)
# x=MaxPooling2D(pool_size=(2,2))(x)
# x=Conv2D(32, (3, 3), padding='same')(x)
# x=Conv2D(32, (3, 3), padding='same')(x)
# x=MaxPooling2D(pool_size=(2,2))(x)
# x=Conv2D(64, (3, 3), padding='same')(x)
# x=Conv2D(64, (3, 3), padding='same')(x)
# x=MaxPooling2D(pool_size=(2,2))(x)
# x=Conv2D(72, (3, 3), padding='same')(x)
# x=Conv2D(72, (3, 3), padding='same')(x)
# x=MaxPooling2D(pool_size=(2,2))(x)
# x=Conv2D(128, (3, 3), padding='same')(x)
# x=Conv2D(128, (3, 3), padding='same')(x)
# x=MaxPooling2D(pool_size=(2,2))(x)
# x=Dropout(0.5)(x)
# x=SReLU()(x)
# x=Flatten()(x)
# # x=Dense(37)(x)
# # x=SReLU()(x)--------------------------------------------------------------0.62(ep-39)

# x=Dense(num_classes)(x)
# #x=SReLU()(x)
# output=Activation('softmax')(x)
# model=Model([inputs], output)

In [133]:
from keras import applications
model = applications.VGG16(weights='imagenet', include_top=False)
print('Model loaded.')

KeyboardInterrupt: 

In [17]:
# inputs=Input(shape=(100,100,1))
# top_model = Sequential()
# top_model.add(Flatten(input_shape=inputs))
# top_model.add(Dense(256, activation='relu'))
# top_model.add(Dropout(0.5))
# top_model.add(Dense(1, activation='sigmoid'))

In [80]:
# inputs=Input(shape=(100,100,1))

# x=Conv2D(16, (3, 3), padding='same')(inputs)
# x=Conv2D(16, (3, 3), padding='same')(x)
# x=MaxPooling2D(pool_size=(2,2))(x)
# x=SReLU()(x)

# x=Conv2D(32, (3, 3), padding='same')(x)
# x=Conv2D(32, (3, 3), padding='same')(x)
# x=MaxPooling2D(pool_size=(2,2))(x)
# x=SReLU()(x)

# x=Conv2D(64, (3, 3), padding='same')(x)
# x=Conv2D(64, (3, 3), padding='same')(x)
# x=MaxPooling2D(pool_size=(2,2))(x)
# x=SReLU()(x)

# x=Conv2D(128, (3, 3), padding='same')(x)
# x=Conv2D(128, (3, 3), padding='same')(x)
# x=MaxPooling2D(pool_size=(2,2))(x)
# x=Dropout(0.2)(x)------------------------------0.96
# x=SReLU()(x)

# x=Flatten()(x)
# x=Dense(num_classes)(x)
# #x=SReLU()(x)
# output=Activation('softmax')(x)
# model=Model([inputs], output)

In [48]:
# inputs = Input((100, 100, 1))
# x =Conv2D(32, (9, 9), padding='same')(inputs)
# x=SReLU()(x)
# x =Conv2D(64, (9, 9), padding='same')(x)
# x=SReLU()(x)
# x = MaxPooling2D((2, 2))(x)
# x = Dropout(0.25)(x)
# x = Flatten()(x)
# x = Dense(240)(x)
# x = Dropout(0.5)(x)
# output=Dense(num_classes, activation='softmax')(x)
# model=Model([inputs], output)

In [49]:
# inputs=Input(shape=(100,100,1))

# x=Conv2D(16, (3, 3), padding='same')(inputs)
# # x=MaxPooling2D(pool_size=(2,2))(x)
# # x=SReLU()(x)

# x=Conv2D(32, (3, 3), padding='same')(x)
# # x=MaxPooling2D(pool_size=(2,2))(x)
# # x=SReLU()(x)

# x=Conv2D(64, (3, 3), padding='same')(x)
# # x=MaxPooling2D(pool_size=(2,2))(x)
# # x=SReLU()(x)

# x=Conv2D(128, (3, 3), padding='same')(x)
# # x=MaxPooling2D(pool_size=(2,2))(x)
# # x=SReLU()(x)

# # x=Conv2D(256, (3, 3), padding='same')(x)
# x=MaxPooling2D(pool_size=(2,2))(x)
# x=Dropout(0.2)(x)
# x=SReLU()(x)

# x=Flatten()(x)
# x=SReLU()(x)
# x=Dense(num_classes)(x)
# #x=SReLU()(x)
# output=Activation('softmax')(x)
# model=Model([inputs], output)

In [175]:
inputs=Input(shape=(100,100,1))

x=Conv2D(16, (3, 3), padding='same')(inputs)
x=SReLU()(x)
x=MaxPooling2D(pool_size=(2,2))(x)


x=Conv2D(32, (3, 3), padding='same')(x)
x=SReLU()(x)
x=MaxPooling2D(pool_size=(2,2))(x)


x=Conv2D(64, (3, 3), padding='same')(x)
x=SReLU()(x)
x=MaxPooling2D(pool_size=(2,2))(x)

x=Conv2D(128, (3, 3), padding='same')(x)
x=SReLU()(x)
x=MaxPooling2D(pool_size=(2,2))(x)
x=Dropout(0.2)(x)
x=Flatten()(x)
x=Dense(num_classes)(x)
output=Activation('softmax')(x)
model=Model([inputs], output)

In [176]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_10 (InputLayer)        (None, 100, 100, 1)       0         
_________________________________________________________________
conv2d_52 (Conv2D)           (None, 100, 100, 16)      160       
_________________________________________________________________
s_re_lu_28 (SReLU)           (None, 100, 100, 16)      640000    
_________________________________________________________________
max_pooling2d_28 (MaxPooling (None, 50, 50, 16)        0         
_________________________________________________________________
conv2d_53 (Conv2D)           (None, 50, 50, 32)        4640      
_________________________________________________________________
s_re_lu_29 (SReLU)           (None, 50, 50, 32)        320000    
_________________________________________________________________
max_pooling2d_29 (MaxPooling (None, 25, 25, 32)        0         
__________

In [177]:
opt=keras.optimizers.RMSprop(lr=1e-3)

In [178]:
model.compile(loss='categorical_crossentropy', optimizer=opt, metrics=['accuracy'])

In [179]:
import h5py
from keras.callbacks import ModelCheckpoint
filepath='E:Dataset_Final(March)/Checkpoints/Level_1/Epoch_41/weights-improvement-{epoch:2d}-{val_acc:.2f}.hdf5'
checkpoint=ModelCheckpoint(filepath, monitor='val_acc', verbose=1, mode='max')

In [180]:
# hist=model.fit_generator(datagen.flow(x_train, y_train,batch_size=batch_size),
#                         epochs=epochs,
#                         validation_data=(x_test, y_test),
#                         callbacks=[checkpoint]
#                )

In [181]:
hist=model.fit(x_train, y_train, 
               batch_size=batch_size,
               epochs=epochs,
               validation_data=(x_test, y_test),
               callbacks=[checkpoint]
               )

Train on 101 samples, validate on 51 samples
Epoch 1/30
101/101 [==============================] - 6s 59ms/step - loss: 3.6838 - acc: 0.0198 - val_loss: 3.6511 - val_acc: 0.0392

Epoch 00001: saving model to E:Dataset_Final(March)/Checkpoints/Level_1/Epoch_41/weights-improvement- 1-0.04.hdf5
Epoch 2/30
101/101 [==============================] - 5s 45ms/step - loss: 3.5493 - acc: 0.0891 - val_loss: 3.5240 - val_acc: 0.0392

Epoch 00002: saving model to E:Dataset_Final(March)/Checkpoints/Level_1/Epoch_41/weights-improvement- 2-0.04.hdf5
Epoch 3/30
101/101 [==============================] - 4s 44ms/step - loss: 3.0459 - acc: 0.1881 - val_loss: 2.8597 - val_acc: 0.2941

Epoch 00003: saving model to E:Dataset_Final(March)/Checkpoints/Level_1/Epoch_41/weights-improvement- 3-0.29.hdf5
Epoch 4/30
101/101 [==============================] - 4s 44ms/step - loss: 2.0361 - acc: 0.4257 - val_loss: 1.8296 - val_acc: 0.4118

Epoch 00004: saving model to E:Dataset_Final(March)/Checkpoints/Level_1/Epoch

In [ ]:
score=model.evaluate(x_test, y_test)

In [ ]:
score[1]

In [ ]:
y_pred=model.predict(x_test)# for dataset of 12 characters
print (y_pred)
y_pred=numpy.argmax(y_pred, axis=1)
print (y_pred)

In [185]:
model.load_weights("E:Dataset_Final(March)/Checkpoints/Level_1/Epoch_41/weights-improvement-14-0.98.hdf5")# f1

In [186]:
score=model.evaluate(x_test, y_test)

51/51 [==============================] - 1s 11ms/step


In [187]:
score[1]

0.98039215686274506

In [188]:
y_pred=model.predict(x_test)# for dataset of 12 characters
print (y_pred)
y_pred=numpy.argmax(y_pred, axis=1)
print (y_pred)

[[  8.56340332e-10   3.57269023e-08   5.51229423e-05 ...,   6.33863584e-09
    7.03464877e-07   5.64237084e-08]
 [  3.62106417e-12   2.62546807e-09   3.85350809e-08 ...,   4.68423607e-12
    3.56244234e-09   3.04301806e-09]
 [  2.36558689e-12   8.08804259e-08   4.07387191e-08 ...,   5.00119147e-11
    9.88002782e-08   4.84607521e-10]
 ..., 
 [  1.93800894e-13   1.02898613e-13   5.18864799e-05 ...,   1.75349557e-09
    2.58499836e-06   9.83416890e-11]
 [  2.66346767e-08   1.46851555e-04   2.63521302e-04 ...,   1.19189145e-02
    1.24375540e-04   5.40804249e-05]
 [  1.23272457e-14   3.74155629e-15   9.99994040e-01 ...,   1.36864777e-08
    3.58358889e-08   1.06472234e-10]]
[19 10 28 29  6 28 11 36 15 37 19  4  2 25  5 24 31 29 18 17 14 16  4 21  1
 22 12 20 21 23 37 17 12 33  5  9  2 13 32 15 23 11 27 22 10 14 27 16 20 11
  2]


In [189]:
print(confusion_matrix(numpy.argmax(y_test, axis=1),y_pred))

[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0

In [190]:

print (classification_report(numpy.argmax(y_test, axis=1), y_pred))

             precision    recall  f1-score   support

          1       1.00      1.00      1.00         1
          2       0.67      1.00      0.80         2
          3       0.00      0.00      0.00         1
          4       1.00      1.00      1.00         2
          5       1.00      1.00      1.00         2
          6       1.00      1.00      1.00         1
          9       1.00      1.00      1.00         1
         10       1.00      1.00      1.00         2
         11       1.00      1.00      1.00         3
         12       1.00      1.00      1.00         2
         13       1.00      1.00      1.00         1
         14       1.00      1.00      1.00         2
         15       1.00      1.00      1.00         2
         16       1.00      1.00      1.00         2
         17       1.00      1.00      1.00         2
         18       1.00      1.00      1.00         1
         19       1.00      1.00      1.00         2
         20       1.00      1.00      1.00   

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [182]:
import pandas

pandas.DataFrame(hist.history).to_csv("E:Dataset_Final(March)/Checkpoints/Level_1/Epoch_41/Figure/History-980.csv")        
# visualizing losses and accuracy
train_loss=hist.history['loss']
val_loss=hist.history['val_loss']
train_acc=hist.history['acc']
val_acc=hist.history['val_acc']
xc=range(epochs)

In [183]:
import matplotlib.pyplot as plt
import matplotlib
from matplotlib.backends.backend_pdf import PdfPages

pp=PdfPages("E:Dataset_Final(March)/Checkpoints/Level_1/Epoch_41/Figure/Loss-980.pdf")
plt.figure(1,figsize=(7,5))
plt.plot(xc,train_loss)
plt.plot(xc,val_loss)
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.title('train_loss vs val_loss')
plt.grid(True)
plt.legend(['train','val'])
print (plt.style.available)
plt.style.use(['classic'])
plt.savefig(pp, format='pdf')
pp.close()

['bmh', 'classic', 'dark_background', 'fast', 'fivethirtyeight', 'ggplot', 'grayscale', 'seaborn-bright', 'seaborn-colorblind', 'seaborn-dark-palette', 'seaborn-dark', 'seaborn-darkgrid', 'seaborn-deep', 'seaborn-muted', 'seaborn-notebook', 'seaborn-paper', 'seaborn-pastel', 'seaborn-poster', 'seaborn-talk', 'seaborn-ticks', 'seaborn-white', 'seaborn-whitegrid', 'seaborn', 'Solarize_Light2', '_classic_test']


In [184]:
pp=PdfPages("E:Dataset_Final(March)/Checkpoints/Level_1/Epoch_41/Figure/Accuracy-980.pdf")
plt.figure(2,figsize=(7,5))
plt.plot(xc,train_acc)
plt.plot(xc,val_acc)
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.title('train_acc vs val_acc')
plt.grid(True)
plt.legend(['train','val'],loc=4)
#print plt.style.available # use bmh, classic,ggplot for big pictures
plt.style.use(['bmh'])
plt.savefig(pp, format='pdf')
pp.close()